#!/usr/bin/env bash
# Displaying information about subdomains

get_info() {
    local domain="$1"
    local subdomain="$2"

    result=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:')

    local record_type
    record_type=$(echo "$result" | awk '/ANSWER SECTION:/ { getline; print $4 }')

    local destination
    destination=$(echo "$result" | awk '/ANSWER SECTION:/ { getline; print $5 }')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ "$#" == 1 ];
then
    get_info "$1" "www"
    get_info "$1" "lb-01"
    get_info "$1" "web-01"
    get_info "$1" "web-02"
elif [ "$#" == 2 ];
then
    get_info "$1" "$2"
fi
