#!/usr/bin/env bash
# This script is displaying Hours and Minutes
hours=0

while [ $hours -le 12 ]; do
    echo "Hour: $hours"

    minutes=1
    while [ $minutes -le 59 ]; do
        echo $minutes
        ((minutes++))
    done
    ((hours++))
done
